local scalescreen = ScrH() / 1080

surface.CreateFont( "AUI_HUD_Font", {
	font = "Arial",
	extended = false,
	size = 22 * scalescreen,
	weight = 900,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "AUI_LAWS_Font", {
	font = "Arial",
	extended = false,
	size = 18 * scalescreen,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "AUI_BLC_Font", {
	font = "Arial",
	extended = false,
	size = 22 * scalescreen,
	weight = 500,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )